plugins {
  id("java")
  id("maven-publish")

  alias(libraries.plugins.champeau.jmh)
}

group = "me.kvdpxne"
version = "0.2.0"

def targetJavaVersion = 8
def javaVersion = JavaVersion.toVersion(targetJavaVersion)

dependencies {
  testImplementation(libraries.bundles.jupiter)
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")

  if (javaVersion.isCompatibleWith(JavaVersion.VERSION_17)) {
    jmh(libraries.bundles.jmh)

    jmhImplementation("co.wosher:jnanoid-enhanced:main-SNAPSHOT")
    //
    //
    jmhImplementation("io.viascom.nanoid:nanoid:1.0.1")
  }
}

java {
  if (JavaVersion.current() < javaVersion) {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
  }

  sourceCompatibility = javaVersion
  targetCompatibility = javaVersion
}

tasks.withType(JavaCompile).configureEach {
  if (10 <= targetJavaVersion || JavaVersion.current().isJava10Compatible()) {
    options.release.set(targetJavaVersion)
  }
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      artifactId = rootProject.name
      groupId = project.group
      version = project.version

      from components.java
    }
  }
}

wrapper {
  distributionType = Wrapper.DistributionType.ALL
}