package me.kvdpxne.forty2; // Zakładamy ten sam pakiet co klasa NanoId

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests focused on detecting potential collisions in the NanoId generator. These are
 * probabilistic tests. A failure indicates a high probability of a problem with the generator's
 * randomness or uniqueness.
 * <p>
 * Note: These tests can be slow and resource-intensive due to large sample sizes. They are good for
 * periodic checks but might not be suitable for every build.
 * </p>
 */
class NanoIdCollisionTest {

  /**
   * Test checking for collisions in a large sample of default NanoIDs generated by
   * {@link NanoId#urlFriendly()} (fast generator). Generates a large number of IDs and asserts that
   * all are unique.
   * <p>
   * This is a probabilistic test. A failure indicates a high probability of a problem with the
   * generator's randomness or uniqueness.
   * </p>
   */
  @Test
  void testRandomDefaultNoCollisionsInLargeSample() {
    final int sampleSize = 50_000; // Adjust based on performance needs / CI limits
    Set<String> generatedIds = new HashSet<>(sampleSize);

    for (int i = 0; i < sampleSize; i++) {
      String id = NanoId.urlFriendly(); // Uses default fast generator and size
      // HashSet.add() returns false if the element already exists
      assertTrue(generatedIds.add(id),
        "Duplicate ID generated by NanoId.random(): " + id + " at iteration " + i +
          ". Sample size: " + sampleSize + ", Current set size: " + generatedIds.size());
    }

    // Final confirmation
    assertEquals(sampleSize, generatedIds.size(), "All generated IDs by NanoId.random() should be unique.");
  }

  /**
   * Test checking for collisions in a large sample of default NanoIDs generated by
   * {@link NanoId#urlFriendlySecure()} (secure generator). Generates a large number of IDs and
   * asserts that all are unique.
   * <p>
   * This is a probabilistic test. A failure indicates a high probability of a problem with the
   * generator's randomness or uniqueness.
   * </p>
   */
  @Test
  void testRandomSecureDefaultNoCollisionsInLargeSample() {
    final int sampleSize = 30_000; // Smaller sample for SecureRandom due to potential performance impact
    Set<String> generatedIds = new HashSet<>(sampleSize);

    for (int i = 0; i < sampleSize; i++) {
      String id = NanoId.urlFriendlySecure(); // Uses default secure generator and size
      // HashSet.add() returns false if the element already exists
      assertTrue(generatedIds.add(id),
        "Duplicate ID generated by NanoId.randomSecure(): " + id + " at iteration " + i +
          ". Sample size: " + sampleSize + ", Current set size: " + generatedIds.size());
    }

    // Final confirmation
    assertEquals(sampleSize, generatedIds.size(), "All generated IDs by NanoId.randomSecure() should be unique.");
  }

  /**
   * Test checking for collisions with a custom alphabet and varying sizes. This tests the core
   * generator logic with user-provided parameters.
   */
  @ParameterizedTest
  @ValueSource(ints = {8, 16, 24, 32, 40})
  // Different sizes to test
  void testCustomAlphabetNoCollisions(int size) {
    final int sampleSize = 100_000;
    // Use a custom alphabet with fewer characters to potentially increase collision chance
    // and make the test more sensitive, though still very unlikely.
    char[] customAlphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789".toCharArray(); // ~32 chars, no look-alikes
    Set<String> generatedIds = new HashSet<>(sampleSize);

    for (int i = 0; i < sampleSize; i++) {
      String id = NanoId.create(customAlphabet, size);
      assertTrue(generatedIds.add(id),
        "Duplicate ID with custom alphabet generated: " + id + " at iteration " + i +
          " with size " + size);
    }
    assertEquals(sampleSize, generatedIds.size(), "All IDs generated with custom alphabet (size " + size + ") should be unique.");
  }

  /**
   * Test checking for collisions using a predefined dictionary method. Tests
   * {@link NanoId#alphanumeric()} and {@link NanoId#alphanumericSecure()} with a large sample.
   */
  @Test
  void testPredefinedDictionaryNoCollisions() {
    final int sampleSizePerMethod = 35_000;

    Set<String> fastIds = new HashSet<>(sampleSizePerMethod);
    Set<String> secureIds = new HashSet<>(sampleSizePerMethod);

    for (int i = 0; i < sampleSizePerMethod; i++) {
      String fastId = NanoId.alphanumeric();
      String secureId = NanoId.alphanumericSecure();

      assertTrue(fastIds.add(fastId),
        "Duplicate ID generated by NanoId.alphanumeric(): " + fastId + " at iteration " + i);
      assertTrue(secureIds.add(secureId),
        "Duplicate ID generated by NanoId.alphanumericSecure(): " + secureId + " at iteration " + i);
    }

    assertEquals(sampleSizePerMethod, fastIds.size(), "All IDs generated by NanoId.alphanumeric() should be unique.");
    assertEquals(sampleSizePerMethod, secureIds.size(), "All IDs generated by NanoId.alphanumericSecure() should be unique.");
  }
}